Add RolesAnywhere Command
square/spiffe-aws-assume-role pull request #30
Opened 2023-04-25 16:56 UTC by brettc-sq

* Added a rolesanywhere command `roles-anywhere-credentials`
* Adjust telemetry options to work via run context

2023-05-05 13:39 UTC, violetd12 approved these changes

2023-05-05 19:17 UTC, jordyn requested changes

2023-05-08 20:09 UTC, brettc-sq commented on cmd/spiffe-aws-assume-role/cli/rolesanywhere_cmd.go
> +			Expiration:      credentials.Expiration.Format(time.RFC3339),
RolesAnywhere's API returns a well-formatted string ready to be consumed by a credentials-process, but the STS API returns a `time.Time` struct that needs conversion!

2023-05-08 20:31 UTC, jordyn approved these changes

2023-05-08 20:39 UTC, merged